wandb_version: 1

batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 8
gamma:
  desc: null
  value: 0.41204073938384367
learning_rate:
  desc: null
  value: 0.005463834184493588
step_Size:
  desc: null
  value: 14
workers:
  desc: null
  value: 2
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709348053.523898
    t:
      1:
      - 1
      - 55
      - 105
      2:
      - 1
      - 55
      - 105
      3:
      - 2
      - 23
      - 37
      4: 3.8.18
      5: 0.16.2
      8:
      - 5
      13: linux-x86_64
